// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: core/v1alpha/data.proto

package core

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Equivaluent to a RDMS' database
type DataBucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Collection *DataCollection `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
}

func (x *DataBucket) Reset() {
	*x = DataBucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_v1alpha_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBucket) ProtoMessage() {}

func (x *DataBucket) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1alpha_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBucket.ProtoReflect.Descriptor instead.
func (*DataBucket) Descriptor() ([]byte, []int) {
	return file_core_v1alpha_data_proto_rawDescGZIP(), []int{0}
}

func (x *DataBucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataBucket) GetCollection() *DataCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

// Equivaluent to a RDMS' database table
type DataCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Documents []*DataDocument `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
}

func (x *DataCollection) Reset() {
	*x = DataCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_v1alpha_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCollection) ProtoMessage() {}

func (x *DataCollection) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1alpha_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCollection.ProtoReflect.Descriptor instead.
func (*DataCollection) Descriptor() ([]byte, []int) {
	return file_core_v1alpha_data_proto_rawDescGZIP(), []int{1}
}

func (x *DataCollection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataCollection) GetDocuments() []*DataDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Equivaluent to a RDMS' database table row
type DataDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DataDocument) Reset() {
	*x = DataDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_v1alpha_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDocument) ProtoMessage() {}

func (x *DataDocument) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1alpha_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDocument.ProtoReflect.Descriptor instead.
func (*DataDocument) Descriptor() ([]byte, []int) {
	return file_core_v1alpha_data_proto_rawDescGZIP(), []int{2}
}

func (x *DataDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataDocument) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_core_v1alpha_data_proto protoreflect.FileDescriptor

var file_core_v1alpha_data_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6e, 0x69, 0x63, 0x6b, 0x6c,
	0x61, 0x77, 0x35, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67,
	0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x45, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6e, 0x69, 0x63, 0x6b, 0x6c, 0x61, 0x77, 0x35, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x67, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a,
	0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x6e, 0x69, 0x63, 0x6b, 0x6c, 0x61, 0x77, 0x35, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x4b, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x63, 0x6b,
	0x6c, 0x61, 0x77, 0x35, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x3b, 0x63, 0x6f, 0x72, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_v1alpha_data_proto_rawDescOnce sync.Once
	file_core_v1alpha_data_proto_rawDescData = file_core_v1alpha_data_proto_rawDesc
)

func file_core_v1alpha_data_proto_rawDescGZIP() []byte {
	file_core_v1alpha_data_proto_rawDescOnce.Do(func() {
		file_core_v1alpha_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_v1alpha_data_proto_rawDescData)
	})
	return file_core_v1alpha_data_proto_rawDescData
}

var file_core_v1alpha_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_v1alpha_data_proto_goTypes = []interface{}{
	(*DataBucket)(nil),      // 0: nicklaw5.core.v1alpha.DataBucket
	(*DataCollection)(nil),  // 1: nicklaw5.core.v1alpha.DataCollection
	(*DataDocument)(nil),    // 2: nicklaw5.core.v1alpha.DataDocument
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_core_v1alpha_data_proto_depIdxs = []int32{
	1, // 0: nicklaw5.core.v1alpha.DataBucket.collection:type_name -> nicklaw5.core.v1alpha.DataCollection
	2, // 1: nicklaw5.core.v1alpha.DataCollection.documents:type_name -> nicklaw5.core.v1alpha.DataDocument
	3, // 2: nicklaw5.core.v1alpha.DataDocument.data:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_v1alpha_data_proto_init() }
func file_core_v1alpha_data_proto_init() {
	if File_core_v1alpha_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_v1alpha_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_v1alpha_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_v1alpha_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_v1alpha_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1alpha_data_proto_goTypes,
		DependencyIndexes: file_core_v1alpha_data_proto_depIdxs,
		MessageInfos:      file_core_v1alpha_data_proto_msgTypes,
	}.Build()
	File_core_v1alpha_data_proto = out.File
	file_core_v1alpha_data_proto_rawDesc = nil
	file_core_v1alpha_data_proto_goTypes = nil
	file_core_v1alpha_data_proto_depIdxs = nil
}
