// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cauldron

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemServiceClient interface {
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
	CreateItemInstance(ctx context.Context, in *CreateItemInstanceRequest, opts ...grpc.CallOption) (*CreateItemInstanceResponse, error)
	GetItemByID(ctx context.Context, in *GetItemByIDRequest, opts ...grpc.CallOption) (*GetItemByIDResponse, error)
	GetItemsByName(ctx context.Context, in *GetItemsByNameRequest, opts ...grpc.CallOption) (*GetItemsByNameResponse, error)
	GetCharacterItems(ctx context.Context, in *GetCharacterItemsRequest, opts ...grpc.CallOption) (*GetCharacterItemsResponse, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	out := new(CreateItemResponse)
	err := c.cc.Invoke(ctx, "/nicklaw5.cauldron.v1alpha.ItemService/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) CreateItemInstance(ctx context.Context, in *CreateItemInstanceRequest, opts ...grpc.CallOption) (*CreateItemInstanceResponse, error) {
	out := new(CreateItemInstanceResponse)
	err := c.cc.Invoke(ctx, "/nicklaw5.cauldron.v1alpha.ItemService/CreateItemInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetItemByID(ctx context.Context, in *GetItemByIDRequest, opts ...grpc.CallOption) (*GetItemByIDResponse, error) {
	out := new(GetItemByIDResponse)
	err := c.cc.Invoke(ctx, "/nicklaw5.cauldron.v1alpha.ItemService/GetItemByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetItemsByName(ctx context.Context, in *GetItemsByNameRequest, opts ...grpc.CallOption) (*GetItemsByNameResponse, error) {
	out := new(GetItemsByNameResponse)
	err := c.cc.Invoke(ctx, "/nicklaw5.cauldron.v1alpha.ItemService/GetItemsByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetCharacterItems(ctx context.Context, in *GetCharacterItemsRequest, opts ...grpc.CallOption) (*GetCharacterItemsResponse, error) {
	out := new(GetCharacterItemsResponse)
	err := c.cc.Invoke(ctx, "/nicklaw5.cauldron.v1alpha.ItemService/GetCharacterItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
// All implementations must embed UnimplementedItemServiceServer
// for forward compatibility
type ItemServiceServer interface {
	CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	CreateItemInstance(context.Context, *CreateItemInstanceRequest) (*CreateItemInstanceResponse, error)
	GetItemByID(context.Context, *GetItemByIDRequest) (*GetItemByIDResponse, error)
	GetItemsByName(context.Context, *GetItemsByNameRequest) (*GetItemsByNameResponse, error)
	GetCharacterItems(context.Context, *GetCharacterItemsRequest) (*GetCharacterItemsResponse, error)
	mustEmbedUnimplementedItemServiceServer()
}

// UnimplementedItemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (UnimplementedItemServiceServer) CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedItemServiceServer) CreateItemInstance(context.Context, *CreateItemInstanceRequest) (*CreateItemInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItemInstance not implemented")
}
func (UnimplementedItemServiceServer) GetItemByID(context.Context, *GetItemByIDRequest) (*GetItemByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemByID not implemented")
}
func (UnimplementedItemServiceServer) GetItemsByName(context.Context, *GetItemsByNameRequest) (*GetItemsByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemsByName not implemented")
}
func (UnimplementedItemServiceServer) GetCharacterItems(context.Context, *GetCharacterItemsRequest) (*GetCharacterItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCharacterItems not implemented")
}
func (UnimplementedItemServiceServer) mustEmbedUnimplementedItemServiceServer() {}

// UnsafeItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemServiceServer will
// result in compilation errors.
type UnsafeItemServiceServer interface {
	mustEmbedUnimplementedItemServiceServer()
}

func RegisterItemServiceServer(s grpc.ServiceRegistrar, srv ItemServiceServer) {
	s.RegisterService(&ItemService_ServiceDesc, srv)
}

func _ItemService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nicklaw5.cauldron.v1alpha.ItemService/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_CreateItemInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateItemInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nicklaw5.cauldron.v1alpha.ItemService/CreateItemInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateItemInstance(ctx, req.(*CreateItemInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetItemByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetItemByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nicklaw5.cauldron.v1alpha.ItemService/GetItemByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetItemByID(ctx, req.(*GetItemByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetItemsByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetItemsByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nicklaw5.cauldron.v1alpha.ItemService/GetItemsByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetItemsByName(ctx, req.(*GetItemsByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetCharacterItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetCharacterItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nicklaw5.cauldron.v1alpha.ItemService/GetCharacterItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetCharacterItems(ctx, req.(*GetCharacterItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemService_ServiceDesc is the grpc.ServiceDesc for ItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nicklaw5.cauldron.v1alpha.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _ItemService_CreateItem_Handler,
		},
		{
			MethodName: "CreateItemInstance",
			Handler:    _ItemService_CreateItemInstance_Handler,
		},
		{
			MethodName: "GetItemByID",
			Handler:    _ItemService_GetItemByID_Handler,
		},
		{
			MethodName: "GetItemsByName",
			Handler:    _ItemService_GetItemsByName_Handler,
		},
		{
			MethodName: "GetCharacterItems",
			Handler:    _ItemService_GetCharacterItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cauldron/v1alpha/item_service.proto",
}
